# Generated by Django 3.2.5 on 2023-02-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewName', models.CharField(max_length=50)),
                ('reviewSurname', models.CharField(max_length=50)),
                ('reviewEmail', models.EmailField(max_length=100)),
                ('reviewQuestion', models.CharField(max_length=1000)),
                ('reviewRating', models.IntegerField()),
            ],
        ),
    ]
