# Generated by Django 3.2.5 on 2023-02-23 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formquestion',
            old_name='reviewEmail',
            new_name='revEmail',
        ),
        migrations.RenameField(
            model_name='formquestion',
            old_name='reviewName',
            new_name='revName',
        ),
        migrations.RenameField(
            model_name='formquestion',
            old_name='reviewQuestion',
            new_name='revQuestion',
        ),
        migrations.RenameField(
            model_name='formquestion',
            old_name='reviewRating',
            new_name='revRating',
        ),
        migrations.RenameField(
            model_name='formquestion',
            old_name='reviewSurname',
            new_name='revSurname',
        ),
    ]
