# Generated by Django 3.2.5 on 2023-02-23 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20230223_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formquestion',
            name='revRating',
        ),
    ]
