# Generated by Django 3.2.5 on 2023-02-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_formquestion_revrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='formquestion',
            name='revRating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
