# Generated by Django 4.1.7 on 2023-03-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_formquestion_revtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formquestion',
            name='revTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
